
dicom_dir: /home/greydon/Documents/GitHub/clinical_dicom2bids_smk/data/dicoms
out_dir: /home/greydon/Documents/GitHub/clinical_dicom2bids_smk/data/output

heuristic: resources/heuristics/clinical_imaging.py

or_dates_file: data/or_dates.tsv

dcm_config: resources/dcm_config.json

anonymize: True

# Session determination
session_calc:
  periop: 0
  dur_multi_surg: -30
  override_periop: True