
dicom_dir: /media/veracrypt6/projects/iEEG/working_dir/dicoms
out_dir: /media/veracrypt6/projects/iEEG/working_dir/out

heuristic: resources/heuristics/clinical_imaging.py

or_dates_file: /media/veracrypt6/projects/iEEG/working_dir/or_dates.tsv

dcm_config: resources/dcm_config.json

anonymize: True

# Session determination
session_calc:
  periop: 0
  dur_multi_surg: -30
  override_periop: True