
#
#--- dicom2bids
#

bids_dir: /home/greydon/data/data/SEEG
#bids_dir: /home/greydon/data/clinical
#bids_dir: /media/stereotaxy/3E7CE0407CDFF11F/data/DBS
#bids_dir: /media/veracrypt6/projects/stealthMRI

heuristic: resources/heuristics/clinical_imaging.py
dcm_config: resources/dcm_config.json

anonymize: False

# Session determination
sort_sessions: True
session_calc:
  peri: 0
  dur_multi_event: -30
  override_peri: True

# subject level settings
sub_group: patient
subject_prefix: 'P'

noncontrast_t1:
    present: False
    acq: False

fastsurfer:
  run: False
  home: "/home/greydon/Documents/GitHub/FastSurfer"
  py: "python3"
  sid: 'fastsurfer'
  batch: 8
  threads: 2
  order: 0    #(0=nearest,1=linear(default),2=quadratic,3=cubic)
  seg_only: True
  vol_segstats: True

fmriprep:
  run: False
  fmriprep_license: resources/license.txt
  bids_filter: resources/bids_filter.json

singularity:
  neuroglia-core: "docker://khanlab/neuroglia-core:latest"
  fastsurfer: "docker://deepmi/fastsurfer:latest"
  freesurfer: "docker://freesurfer/freesurfer:latest"
  fmriprep: resources/fmriprep-21.0.0.simg
