
#
#--- dicom2bids
#

dicom_dir: /home/greydon/Downloads/PPMI/dicoms
out_dir: /home/greydon/Downloads/PPMI/out
clinical_event_file: 
participants_tsv:

heuristic: resources/heuristics/ppmi_heuristic.py
dcm_config: resources/dcm_config.json

anonymize: False

# Session determination
sort_sessions: False
session_calc:
  peri: 0
  dur_multi_event: -30
  override_peri: True

# subject level settings
sub_group: patient
subject_prefix: P
