
#
#--- dicom2bids
#

dicom_dir: /home/greydon/Documents/GitHub/clinical_dicom2bids_smk/data/dicoms
out_dir: /home/greydon/Documents/GitHub/clinical_dicom2bids_smk/data/output
clinical_event_file: /home/greydon/Documents/GitHub/clinical_dicom2bids_smk/data/clinical_events.tsv
participants_tsv:

heuristic: resources/heuristics/clinical_imaging.py
dcm_config: resources/dcm_config.json

anonymize: True

# Session determination
session_calc:
  peri: 0
  dur_multi_event: -30
  override_peri: True

# subject level settings
sub_group: patient
subject_prefix: P
