
#
#--- dicom2bids
#

bids_dir: /home/greydon/Documents/data/DBS

#bids_dir: /media/stereotaxy/3E7CE0407CDFF11F/data/DBS

heuristic: resources/heuristics/clinical_imaging.py
dcm_config: resources/dcm_config.json

anonymize: False

# Session determination
sort_sessions: True
session_calc:
  peri: 0
  dur_multi_event: -30
  override_peri: True

# subject level settings
sub_group: patient
subject_prefix: P

fastsurfer:
  run: False
  home: "/home/greydon/Documents/GitHub/FastSurfer"
  py: "python3"
  sid: 'fastsurfer'
  batch: 16
  order: 0    #(0=nearest,1=linear(default),2=quadratic,3=cubic)
  seg_only: True
  vol_segstats: True

fmriprep:
  run: True
  fmriprep_license: resources/license.txt

singularity:
  neuroglia-core: "docker://khanlab/neuroglia-core:latest"
  fastsurfer: "docker://deepmi/fastsurfer:latest"
  freesurfer: "docker://freesurfer/freesurfer:latest"
  fmriprep: .snakemake/singularity/02f848ff41039b07932048d9371c7c4a.simg
